### PR TITLE
Improvements to goodbye plugin.

### PR DESCRIPTION
**Pull request by danmarsden**
Move link to my profile navigation.
prevent admin accounts from being deleted.
force logout correctly after deletion.
don't redirect but display a confirmation page after deletion.

### CODE REVIEW

**Comment by danmarsden** [comment]
Here's a patch with some changes I made to add support for manual accounts and a few other minor changes like moving the link to delete the account under the "My profile" area.

Feel free to reject these if you think they aren't useful - also I've only tested this on a clients Totara 2.4 site so it might be worth checking to make sure the profile link change still works in newer versions of Moodle.

**Comment by bmbrands** [comment]
Awesome, thanks for your improvements! It's been a while since I have done any updates on this and it is nice to know it is actually being used!
Cheers!

**Comment by bmbrands** [comment]
Now updated on Moodle.org too!

**Comment by danmarsden** [comment]
That was quick! - I just had our client ask us to move it from the navigation block and into the settings block under my profile which I think makes more sense as it provides similar links such as edit profile/change password etc. I'll file another pull request with that patch for you to review. (I haven't tested this on anything newer than 2.4 as the client is using an older Totara 2.4 release.)

**Pull request merged**
